const words = [
  { num: 1, unit: 1, eng: "complain", kor: "항의하다, 불만을 털어놓다" },
  { num: 2, unit: 1, eng: "work", kor: "작동하다; 효과가 있다" },
  { num: 3, unit: 1, eng: "refund", kor: "환불" },
  { num: 4, unit: 1, eng: "warranty", kor: "품질 보증(서)" },
  { num: 5, unit: 1, eng: "replace A with B", kor: "A를 B로 바꾸다, 교환하다" },
  { num: 6, unit: 1, eng: "receipt", kor: "영수증" },
  { num: 7, unit: 1, eng: "dealer", kor: "판매인" },
  { num: 8, unit: 1, eng: "on the spot", kor: "그 자리에서 바로, 즉석에서" },
  { num: 9, unit: 1, eng: "satisfaction", kor: "만족" },
  { num: 10, unit: 1, eng: "customer", kor: "고객" },
  { num: 11, unit: 1, eng: "policy", kor: "정책, 방침" },
  { num: 12, unit: 1, eng: "employee", kor: "사원, 직원" },
  { num: 13, unit: 1, eng: "gain", kor: "얻다, 획득하다" },
  { num: 14, unit: 1, eng: "experience", kor: "경험; 경험하다" },
  { num: 15, unit: 1, eng: "department", kor: "부서, 과" },
  { num: 16, unit: 1, eng: "complete", kor: "채우다; 완료하다" },
  { num: 17, unit: 1, eng: "look forward to", kor: "~하기를 기대하다" },
  { num: 18, unit: 1, eng: "training", kor: "교육, 훈련" },
  { num: 19, unit: 1, eng: "personnel", kor: "인사의" },
  { num: 20, unit: 1, eng: "announce", kor: "알리다; 발표하다" },
  { num: 21, unit: 1, eng: "opening", kor: "개업, 개점" },
  { num: 22, unit: 1, eng: "quality", kor: "양질의; 질" },
  { num: 23, unit: 1, eng: "product", kor: "제품, 상품" },
  { num: 24, unit: 1, eng: "attractive", kor: "매력적인" },
  { num: 25, unit: 1, eng: "location", kor: "장소, 위치" },
  { num: 26, unit: 1, eng: "branch", kor: "지점" },
  { num: 27, unit: 1, eng: "principal", kor: "교장" },
  { num: 28, unit: 1, eng: "education", kor: "교육" },
  { num: 29, unit: 1, eng: "require", kor: "(~로 하여금) 요구하다; 필요로 하다" },
  { num: 30, unit: 1, eng: "miss", kor: "(학교·수업에) 결석하다, 빠지다" },
  { num: 31, unit: 1, eng: "athlete", kor: "운동선수" },
  { num: 32, unit: 1, eng: "opportunity", kor: "기회" },
  { num: 33, unit: 1, eng: "understanding", kor: "이해" },
  { num: 34, unit: 1, eng: "brief", kor: "간단한; (기간이) 짧은" },
  { num: 35, unit: 1, eng: "subscription", kor: "구독(료)" },
  { num: 36, unit: 1, eng: "renew", kor: "갱신(연장)하다" },
  { num: 37, unit: 1, eng: "upcoming", kor: "곧 있을, 다가오는" },
  { num: 38, unit: 1, eng: "issue", kor: "(출판물의) 호" },
  { num: 39, unit: 1, eng: "continue", kor: "지속하다, 계속하다" },
  { num: 40, unit: 1, eng: "monthly", kor: "매달의, 월 1회의" },
  { num: 41, unit: 2, eng: "dive", kor: "잠수하다" },
  { num: 42, unit: 2, eng: "sink", kor: "가라앉다" },
  { num: 43, unit: 2, eng: "run out", kor: "다 떨어지다" },
  { num: 44, unit: 2, eng: "remove", kor: "벗다, 제거하다" },
  { num: 45, unit: 2, eng: "lift", kor: "들어 올리다" },
  { num: 46, unit: 2, eng: "appear", kor: "나타나다" },
  { num: 47, unit: 2, eng: "look into", kor: "~의 속을 들여다 보다, 주의 깊게 살펴보다" },
  { num: 48, unit: 2, eng: "save", kor: "보호하다" },
  { num: 49, unit: 2, eng: "surface", kor: "수면, 표면" },
  { num: 50, unit: 2, eng: "fancy", kor: "멋진, 화려한" },
  { num: 51, unit: 2, eng: "label", kor: "표, 상표" },
  { num: 52, unit: 2, eng: "be ready for", kor: "~할 준비가 되다" },
  { num: 53, unit: 2, eng: "picture", kor: "상상하다, 마음속에 그리다" },
  { num: 54, unit: 2, eng: "shine", kor: "(태양이) 비치다; 빛나다" },
  { num: 55, unit: 2, eng: "mild", kor: "온화한" },
  { num: 56, unit: 2, eng: "breeze", kor: "산들바람" },
  { num: 57, unit: 2, eng: "slight", kor: "약간의, 조금의" },
  { num: 58, unit: 2, eng: "spread", kor: "(더 넓은 범위로) 번지다" },
  { num: 59, unit: 2, eng: "turn over", kor: "몸(자세)을 뒤집다" },
  { num: 60, unit: 2, eng: "scent", kor: "향기" },
  { num: 61, unit: 2, eng: "trunk", kor: "나무의 몸통" },
  { num: 62, unit: 2, eng: "concern", kor: "걱정, 염려" },
  { num: 63, unit: 2, eng: "go away", kor: "사라지다" },
  { num: 64, unit: 2, eng: "tie", kor: "묶다" },
  { num: 65, unit: 2, eng: "leather", kor: "가죽" },
  { num: 66, unit: 2, eng: "wedding ceremony", kor: "결혼식" },
  { num: 67, unit: 2, eng: "celebration", kor: "축하 행사" },
  { num: 68, unit: 2, eng: "joyful", kor: "즐거운" },
  { num: 69, unit: 2, eng: "shake", kor: "흔들다" },
  { num: 70, unit: 2, eng: "clap", kor: "(손뼉을) 치다" },
  { num: 71, unit: 2, eng: "freeze", kor: "(몸·표정이) 굳다" },
  { num: 72, unit: 2, eng: "control", kor: "통제하다" },
  { num: 73, unit: 2, eng: "have trouble -ing", kor: "~하는 데 어려움을 겪다" },
  { num: 74, unit: 2, eng: "airspeed", kor: "풍속" },
  { num: 75, unit: 2, eng: "report", kor: "보고하다" },
  { num: 76, unit: 2, eng: "emergency", kor: "비상사태" },
  { num: 77, unit: 2, eng: "bump", kor: "부딪치다" },
  { num: 78, unit: 2, eng: "by accident", kor: "우연히" },
  { num: 79, unit: 2, eng: "regain", kor: "되살아나다, 회복하다" },
  { num: 80, unit: 2, eng: "loosen up", kor: "긴장을 풀다" },
  { num: 81, unit: 3, eng: "worldwide", kor: "전 세계" },
  { num: 82, unit: 3, eng: "list", kor: "목록" },
  { num: 83, unit: 3, eng: "follow", kor: "~의 뒤를 잇다" },
  { num: 84, unit: 3, eng: "consumption", kor: "소비" },
  { num: 85, unit: 3, eng: "social network", kor: "소셜 네트워크" },
  { num: 86, unit: 3, eng: "mostly", kor: "주로" },
  { num: 87, unit: 3, eng: "popular", kor: "인기 있는" },
  { num: 88, unit: 3, eng: "daily", kor: "하루의, 매일의" },
  { num: 89, unit: 3, eng: "usage", kor: "사용" },
  { num: 90, unit: 3, eng: "device", kor: "기기, 장치" },
  { num: 91, unit: 3, eng: "mobile", kor: "휴대 전화" },
  { num: 92, unit: 3, eng: "spend", kor: "(시간을) 보내다; (돈을) 쓰다" },
  { num: 93, unit: 3, eng: "overall", kor: "전반적으로" },
  { num: 94, unit: 3, eng: "increase", kor: "증가하다" },
  { num: 95, unit: 3, eng: "steadily", kor: "꾸준하게" },
  { num: 96, unit: 3, eng: "desktop", kor: "탁상용 컴퓨터" },
  { num: 97, unit: 3, eng: "laptop", kor: "노트북(컴퓨터)" },
  { num: 98, unit: 3, eng: "account for", kor: "(부분·비율을) 차지하다" },
  { num: 99, unit: 3, eng: "result", kor: "결과" },
  { num: 100, unit: 3, eng: "survey", kor: "조사" },
  { num: 101, unit: 3, eng: "invention", kor: "발명" },
  { num: 102, unit: 3, eng: "interest", kor: "흥미, 관심" },
  { num: 103, unit: 3, eng: "young adult", kor: "청소년, 성인기 초반의 사람" },
  { num: 104, unit: 3, eng: "category", kor: "범주" },
  { num: 105, unit: 3, eng: "respondent", kor: "응답자" },
  { num: 106, unit: 3, eng: "consumer", kor: "소비자" },
  { num: 107, unit: 3, eng: "female", kor: "여성의" },
  { num: 108, unit: 3, eng: "male", kor: "남성; 남성의" },
  { num: 109, unit: 3, eng: "environmental", kor: "환경의" },
  { num: 110, unit: 3, eng: "gender", kor: "성별" },
  { num: 111, unit: 4, eng: "passenger", kor: "승객" },
  { num: 112, unit: 4, eng: "flight", kor: "비행" },
  { num: 113, unit: 4, eng: "unfortunately", kor: "불행하게도" },
  { num: 114, unit: 4, eng: "injury", kor: "부상" },
  { num: 115, unit: 4, eng: "career", kor: "직업, 경력" },
  { num: 116, unit: 4, eng: "degree", kor: "학위" },
  { num: 117, unit: 4, eng: "name after", kor: "~을 따서 이름 짓다" },
  { num: 118, unit: 4, eng: "frightened", kor: "겁먹은, 무서워하는" },
  { num: 119, unit: 4, eng: "childhood", kor: "어린 시절, 유년 시절" },
  { num: 120, unit: 4, eng: "major in", kor: "~을 전공하다" },
  { num: 121, unit: 4, eng: "congresswoman", kor: "여성 하원 의원" },
  { num: 122, unit: 4, eng: "against", kor: "~에 반대하여" },
  { num: 123, unit: 4, eng: "involvement", kor: "개입" },
  { num: 124, unit: 4, eng: "expansion", kor: "확장" },
  { num: 125, unit: 4, eng: "development", kor: "개발; 발달, 성장" },
  { num: 126, unit: 4, eng: "weigh", kor: "무게가 나가다" },
  { num: 127, unit: 4, eng: "mature", kor: "다 자란; 성숙한" },
  { num: 128, unit: 4, eng: "shiny", kor: "윤기가 나는, 빛나는" },
  { num: 129, unit: 4, eng: "disappear", kor: "사라지다" },
  { num: 130, unit: 4, eng: "distinguish", kor: "구별하다" },
  { num: 131, unit: 4, eng: "resemble", kor: "닮다, 비슷하다" },
  { num: 132, unit: 4, eng: "behavior", kor: "행동" },
  { num: 133, unit: 4, eng: "regulate", kor: "조절하다" },
  { num: 134, unit: 4, eng: "temperature", kor: "온도, 기온" },
  { num: 135, unit: 4, eng: "generate", kor: "발생시키다, 만들어 내다" },
  { num: 136, unit: 4, eng: "take in", kor: "~을 섭취하다" },
  { num: 137, unit: 4, eng: "escape", kor: "벗어나다, 빠져나오다; 피하다" },
  { num: 138, unit: 4, eng: "feather", kor: "깃털" },
  { num: 139, unit: 4, eng: "layer", kor: "층, 겹" },
  { num: 140, unit: 4, eng: "extreme", kor: "극도로, 극심한" },
  { num: 141, unit: 4, eng: "shiver", kor: "(몸을) 떨다" },
  { num: 142, unit: 4, eng: "surrounding", kor: "주위의" },
  { num: 143, unit: 4, eng: "advantage", kor: "이점" },
  { num: 144, unit: 4, eng: "actively", kor: "적극적으로" },
  { num: 145, unit: 4, eng: "approve", kor: "찬성하다" },
  { num: 146, unit: 4, eng: "desire", kor: "갈망, 바람" },
  { num: 147, unit: 4, eng: "admire", kor: "감탄하다, 존경하다" },
  { num: 148, unit: 4, eng: "inspiration", kor: "영감" },
  { num: 149, unit: 4, eng: "portrait", kor: "초상화" },
  { num: 150, unit: 4, eng: "sight", kor: "시력" },
  { num: 151, unit: 5, eng: "selfie", kor: "셀카 사진" },
  { num: 152, unit: 5, eng: "competition", kor: "대회" },
  { num: 153, unit: 5, eng: "prize", kor: "상" },
  { num: 154, unit: 5, eng: "deadline", kor: "마감 기한" },
  { num: 155, unit: 5, eng: "detail", kor: "세부 사항" },
  { num: 156, unit: 5, eng: "creative", kor: "창의적인" },
  { num: 157, unit: 5, eng: "entry", kor: "출품작" },
  { num: 158, unit: 5, eng: "winner", kor: "수상자" },
  { num: 159, unit: 5, eng: "comfortable", kor: "편안한" },
  { num: 160, unit: 5, eng: "provide", kor: "제공하다" },
  { num: 161, unit: 5, eng: "registration", kor: "등록" },
  { num: 162, unit: 5, eng: "at least", kor: "적어도, 최소한" },
  { num: 163, unit: 5, eng: "function", kor: "기능" },
  { num: 164, unit: 5, eng: "background", kor: "배경 화면" },
  { num: 165, unit: 5, eng: "decrease", kor: "줄이다" },
  { num: 166, unit: 5, eng: "caution", kor: "주의 사항" },
  { num: 167, unit: 5, eng: "choir", kor: "합창단" },
  { num: 168, unit: 5, eng: "audition", kor: "오디션" },
  { num: 169, unit: 5, eng: "performance", kor: "공연" },
  { num: 170, unit: 5, eng: "freshman", kor: "신입생" },
  { num: 171, unit: 5, eng: "auditorium", kor: "강당" },
  { num: 172, unit: 5, eng: "applicant", kor: "지원자" },
  { num: 173, unit: 5, eng: "participate in", kor: "~에 참가하다" },
  { num: 174, unit: 5, eng: "select", kor: "선택하다" },
  { num: 175, unit: 5, eng: "grand prize", kor: "대상" },
  { num: 176, unit: 5, eng: "voting", kor: "투표" },
  { num: 177, unit: 5, eng: "submission", kor: "제출" },
  { num: 178, unit: 5, eng: "participant", kor: "참가자" },
  { num: 179, unit: 5, eng: "submit", kor: "제출하다" },
  { num: 180, unit: 5, eng: "include", kor: "포함하다" },
  { num: 181, unit: 6, eng: "aspect", kor: "측면, 양상" },
  { num: 182, unit: 6, eng: "soothing", kor: "진정하는" },
  { num: 183, unit: 6, eng: "consider", kor: "고려하다" },
  { num: 184, unit: 6, eng: "material", kor: "천, 직물" },
  { num: 185, unit: 6, eng: "property", kor: "속성, 특성" },
  { num: 186, unit: 6, eng: "form", kor: "만들다, 형성하다" },
  { num: 187, unit: 6, eng: "be made up of", kor: "~으로 구성되다[이루어지다]" },
  { num: 188, unit: 6, eng: "tiny", kor: "미세한, 작은" },
  { num: 189, unit: 6, eng: "bit", kor: "(한) 조각" },
  { num: 190, unit: 6, eng: "glacier", kor: "빙하" },
  { num: 191, unit: 6, eng: "factor", kor: "요인, 요소" },
  { num: 192, unit: 6, eng: "determine", kor: "결정하다" },
  { num: 193, unit: 6, eng: "enemy", kor: "적" },
  { num: 194, unit: 6, eng: "essential", kor: "필수적인" },
  { num: 195, unit: 6, eng: "drown", kor: "물에 빠뜨리다, 익사하다" },
  { num: 196, unit: 6, eng: "knowledge", kor: "지식" },
  { num: 197, unit: 6, eng: "exception", kor: "예외, 제외" },
  { num: 198, unit: 6, eng: "suffer from", kor: "~로부터 고통 받다" },
  { num: 199, unit: 6, eng: "investment", kor: "투자" },
  { num: 200, unit: 6, eng: "storyteller", kor: "스토리텔러, 이야기꾼" },
  { num: 201, unit: 6, eng: "hang on", kor: "~을 걸다[매달다]" },
  { num: 202, unit: 6, eng: "historical", kor: "역사적인" },
  { num: 203, unit: 6, eng: "currently", kor: "현재, 지금" },
  { num: 204, unit: 6, eng: "dramatic", kor: "극적인" },
  { num: 205, unit: 6, eng: "discussion", kor: "토의" },
  { num: 206, unit: 6, eng: "further", kor: "더, 더욱 더" },
  { num: 207, unit: 6, eng: "indicate", kor: "보여 주다, 나타내다" },
  { num: 208, unit: 6, eng: "impressive", kor: "인상적인" },
  { num: 209, unit: 6, eng: "method", kor: "방법" },
  { num: 210, unit: 6, eng: "cite", kor: "인용하다" },
  { num: 211, unit: 6, eng: "saying", kor: "격언, 속담" },
  { num: 212, unit: 6, eng: "immediate", kor: "즉각적인" },
  { num: 213, unit: 6, eng: "interaction", kor: "상호 작용" },
  { num: 214, unit: 6, eng: "encounter", kor: "만남" },
  { num: 215, unit: 6, eng: "response", kor: "반응" },
  { num: 216, unit: 6, eng: "familiarity", kor: "친밀감" },
  { num: 217, unit: 6, eng: "overcome", kor: "극복하다" },
  { num: 218, unit: 6, eng: "natural", kor: "당연한" },
  { num: 219, unit: 6, eng: "hesitancy", kor: "머뭇거림" },
  { num: 220, unit: 6, eng: "mutual", kor: "상호의" },
  { num: 221, unit: 7, eng: "float around", kor: "(생각·소문 등이) 떠돌다" },
  { num: 222, unit: 7, eng: "ensure", kor: "반드시 ~하게 하다; 보장하다" },
  { num: 223, unit: 7, eng: "record", kor: "기록하다" },
  { num: 224, unit: 7, eng: "aim", kor: "목표로 하다" },
  { num: 225, unit: 7, eng: "hit", kor: "(특정 수준·정도)에 이르다" },
  { num: 226, unit: 7, eng: "reminder", kor: "상기시키는 것, 생각나게 하는 것" },
  { num: 227, unit: 7, eng: "motivator", kor: "동기를 부여하는 것" },
  { num: 228, unit: 7, eng: "burden", kor: "부담, 짐" },
  { num: 229, unit: 7, eng: "finding", kor: "(조사·연구 등의) 발견" },
  { num: 230, unit: 7, eng: "formation", kor: "형성" },
  { num: 231, unit: 7, eng: "positive", kor: "긍정적으로" },
  { num: 232, unit: 7, eng: "acquire", kor: "익히다, 습득하다" },
  { num: 233, unit: 7, eng: "impulsive", kor: "충동적인" },
  { num: 234, unit: 7, eng: "regularly", kor: "규칙적으로" },
  { num: 235, unit: 7, eng: "condition", kor: "조건" },
  { num: 236, unit: 7, eng: "tool", kor: "도구" },
  { num: 237, unit: 7, eng: "cultivate", kor: "함양하다, 기르다" },
  { num: 238, unit: 7, eng: "calligrapher", kor: "서예가" },
  { num: 239, unit: 7, eng: "capacity", kor: "능력" },
  { num: 240, unit: 7, eng: "lonely", kor: "외로운" },
  { num: 241, unit: 7, eng: "shared", kor: "공동된, 공유된" },
  { num: 242, unit: 7, eng: "purpose", kor: "목적" },
  { num: 243, unit: 7, eng: "be engaged in", kor: "~에 관여[참여]하다" },
  { num: 244, unit: 7, eng: "volunteer", kor: "자원봉사하다; 자원봉사자" },
  { num: 245, unit: 7, eng: "be satisfied with", kor: "~에 만족하다" },
  { num: 246, unit: 7, eng: "enrich", kor: "풍부하게 하다" },
  { num: 247, unit: 7, eng: "loneliness", kor: "외로움" },
  { num: 248, unit: 7, eng: "benefit", kor: "혜택을 받다" },
  { num: 249, unit: 7, eng: "voluntary", kor: "자발적인; 자원봉사의" },
  { num: 250, unit: 7, eng: "attain", kor: "얻다, 이루다" },
  { num: 251, unit: 7, eng: "settle for", kor: "~에 안주하다" },
  { num: 252, unit: 7, eng: "mindset", kor: "사고방식, 마음가짐" },
  { num: 253, unit: 7, eng: "approach", kor: "접근하다; 접근법" },
  { num: 254, unit: 7, eng: "impact", kor: "영향을 끼치다" },
  { num: 255, unit: 7, eng: "mood", kor: "기분" },
  { num: 256, unit: 7, eng: "productive", kor: "생산적인" },
  { num: 257, unit: 7, eng: "productivity", kor: "생산성" },
  { num: 258, unit: 7, eng: "promotion", kor: "승진" },
  { num: 259, unit: 7, eng: "raise", kor: "임금 인상" },
  { num: 260, unit: 7, eng: "consequently", kor: "결과적으로" },
  { num: 261, unit: 8, eng: "temper", kor: "화" },
  { num: 262, unit: 8, eng: "argument", kor: "논쟁, 논거" },
  { num: 263, unit: 8, eng: "annoy", kor: "화나게 하다" },
  { num: 264, unit: 8, eng: "respond", kor: "대답하다" },
  { num: 265, unit: 8, eng: "remark", kor: "발언" },
  { num: 266, unit: 8, eng: "effective", kor: "효과적인" },
  { num: 267, unit: 8, eng: "attentive", kor: "주의 깊은" },
  { num: 268, unit: 8, eng: "concept", kor: "개념" },
  { num: 269, unit: 8, eng: "argue", kor: "주장하다" },
  { num: 270, unit: 8, eng: "virtuous", kor: "미덕이 있는, 덕이 높은" },
  { num: 271, unit: 8, eng: "deceive", kor: "속이다" },
  { num: 272, unit: 8, eng: "trait", kor: "특성" },
  { num: 273, unit: 8, eng: "maximize", kor: "극대화하다" },
  { num: 274, unit: 8, eng: "virtue", kor: "미덕" },
  { num: 275, unit: 8, eng: "generous", kor: "관대한" },
  { num: 276, unit: 8, eng: "extremely", kor: "매우, 대단히; 극히" },
  { num: 277, unit: 8, eng: "repetition", kor: "반복" },
  { num: 278, unit: 8, eng: "motivate", kor: "~할 동기를 부여하다" },
  { num: 279, unit: 8, eng: "sharpen", kor: "(날카롭게) 깎다; 연마하다" },
  { num: 280, unit: 8, eng: "valuable", kor: "가치 있는" },
  { num: 281, unit: 8, eng: "passion", kor: "열정" },
  { num: 282, unit: 8, eng: "recognize", kor: "인정하다, 인식하다" },
  { num: 283, unit: 8, eng: "employ", kor: "사용하다" },
  { num: 284, unit: 8, eng: "bond", kor: "유대" },
  { num: 285, unit: 8, eng: "enhance", kor: "높이다, 향상시키다" },
  { num: 286, unit: 8, eng: "assume", kor: "가정하다" },
  { num: 287, unit: 8, eng: "discourse", kor: "담화" },
  { num: 288, unit: 8, eng: "establish", kor: "확립하다, 설립하다" },
  { num: 289, unit: 8, eng: "identity", kor: "정체성" },
  { num: 290, unit: 8, eng: "obtain", kor: "얻다, 획득하다" },
  { num: 291, unit: 8, eng: "exclude", kor: "배제하다, 제외하다" },
  { num: 292, unit: 8, eng: "deliberately", kor: "의도적으로" },
  { num: 293, unit: 8, eng: "personality", kor: "개성" },
  { num: 294, unit: 8, eng: "associate", kor: "연관 짓다" },
  { num: 295, unit: 8, eng: "treadmill", kor: "쳇바퀴" },
  { num: 296, unit: 8, eng: "satisfy", kor: "충족시키다, 만족시키다" },
  { num: 297, unit: 8, eng: "longing", kor: "바람, 갈망" },
  { num: 298, unit: 8, eng: "silence", kor: "잠재우다, 잠잠하게 하다" },
  { num: 299, unit: 8, eng: "chase", kor: "뒤쫓다, 추구하다" },
  { num: 300, unit: 8, eng: "definition", kor: "정의" },
  { num: 301, unit: 9, eng: "defeat", kor: "패배하다" },
  { num: 302, unit: 9, eng: "rival", kor: "경쟁하는" },
  { num: 303, unit: 9, eng: "create", kor: "창조하다" },
  { num: 304, unit: 9, eng: "blessing", kor: "축복" },
  { num: 305, unit: 9, eng: "complaint", kor: "불평" },
  { num: 306, unit: 9, eng: "bendable", kor: "구부릴 수 있는" },
  { num: 307, unit: 9, eng: "get rid of", kor: "~을 제거하다" },
  { num: 308, unit: 9, eng: "cheerful", kor: "유쾌한" },
  { num: 309, unit: 9, eng: "nod", kor: "(고개를) 끄덕이다" },
  { num: 310, unit: 9, eng: "drop", kor: "내려놓다" },
  { num: 311, unit: 9, eng: "stare", kor: "바라보다, 응시하다" },
  { num: 312, unit: 9, eng: "lab", kor: "실험실 (= laboratory)" },
  { num: 313, unit: 9, eng: "practice", kor: "연습하다" },
  { num: 314, unit: 9, eng: "succeed", kor: "성공하다" },
  { num: 315, unit: 9, eng: "injure", kor: "다치다" },
  { num: 316, unit: 9, eng: "realize", kor: "깨닫다" },
  { num: 317, unit: 9, eng: "bracelet", kor: "팔찌" },
  { num: 318, unit: 9, eng: "troubled", kor: "괴로워하는" },
  { num: 319, unit: 9, eng: "guilt", kor: "죄책감; 유죄" },
  { num: 320, unit: 9, eng: "quietly", kor: "조용히; 침착하게" },
  { num: 321, unit: 9, eng: "punish", kor: "벌하다, 처벌하다" },
  { num: 322, unit: 9, eng: "tear up", kor: "(종이를) 갈기갈기 찢다[찢어버리다]" },
  { num: 323, unit: 9, eng: "forgive", kor: "용서하다" },
  { num: 324, unit: 9, eng: "vehicle", kor: "차, 교통수단" },
  { num: 325, unit: 9, eng: "teenager", kor: "십 대" },
  { num: 326, unit: 9, eng: "frustration", kor: "절망, 좌절" },
  { num: 327, unit: 9, eng: "explain", kor: "설명하다" },
  { num: 328, unit: 9, eng: "situation", kor: "상황" },
  { num: 329, unit: 9, eng: "round trip", kor: "왕복" },
  { num: 330, unit: 9, eng: "sunset", kor: "석양, 일몰" },
  { num: 331, unit: 10, eng: "completely", kor: "완전히" },
  { num: 332, unit: 10, eng: "process", kor: "과정" },
  { num: 333, unit: 10, eng: "heal", kor: "치유하다" },
  { num: 334, unit: 10, eng: "normally", kor: "정상적으로, 보통" },
  { num: 335, unit: 10, eng: "patience", kor: "인내" },
  { num: 336, unit: 10, eng: "suspicious", kor: "의심하는" },
  { num: 337, unit: 10, eng: "rapid", kor: "빠른" },
  { num: 338, unit: 10, eng: "desirable", kor: "바람직한" },
  { num: 339, unit: 10, eng: "available", kor: "이용 가능한" },
  { num: 340, unit: 10, eng: "consideration", kor: "숙고" },
  { num: 341, unit: 10, eng: "particularly", kor: "특히" },
  { num: 342, unit: 10, eng: "impression", kor: "인상" },
  { num: 343, unit: 10, eng: "make sense of", kor: "~을 파악하다[이해하다]" },
  { num: 344, unit: 10, eng: "survivor", kor: "생존자" },
  { num: 345, unit: 10, eng: "mark", kor: "나타내다, 표시하다" },
  { num: 346, unit: 10, eng: "attraction", kor: "매력 요소, 사람의 관심을 끄는 것" },
  { num: 347, unit: 10, eng: "decoration", kor: "장식물" },
  { num: 348, unit: 10, eng: "appeal", kor: "관심을 끌다" },
  { num: 349, unit: 10, eng: "specific", kor: "특정한" },
  { num: 350, unit: 10, eng: "dairy", kor: "유제품" },
  { num: 351, unit: 10, eng: "frequently", kor: "자주, 흔히" },
  { num: 352, unit: 10, eng: "experiment", kor: "실험" },
  { num: 353, unit: 10, eng: "trick", kor: "속임수" },
  { num: 354, unit: 10, eng: "inspire", kor: "영감을 주다" },
  { num: 355, unit: 10, eng: "proceed", kor: "계속해서 ~하다" },
  { num: 356, unit: 10, eng: "rationalize", kor: "합리화하다" },
  { num: 357, unit: 10, eng: "observe", kor: "관찰하다" },
  { num: 358, unit: 10, eng: "domain", kor: "분야, 영역" },
  { num: 359, unit: 10, eng: "financial", kor: "금전상의" },
  { num: 360, unit: 10, eng: "norm", kor: "규범" },
  { num: 361, unit: 10, eng: "reflect", kor: "반영하다, 나타내다" },
  { num: 362, unit: 10, eng: "significance", kor: "의미" },
  { num: 363, unit: 10, eng: "translate", kor: "전환하다" },
  { num: 364, unit: 10, eng: "cooperation", kor: "협력, 협동" },
  { num: 365, unit: 10, eng: "literature", kor: "문학" },
  { num: 366, unit: 10, eng: "emphasize", kor: "강조하다" },
  { num: 367, unit: 10, eng: "internalize", kor: "내재화하다" },
  { num: 368, unit: 10, eng: "sincere", kor: "진실한, 진심 어린" },
  { num: 369, unit: 10, eng: "absence", kor: "부재" },
  { num: 370, unit: 10, eng: "relevant", kor: "관련된" },
  { num: 371, unit: 11, eng: "pay attention to", kor: "~에 주의를 기울이다" },
  { num: 372, unit: 11, eng: "dismissive", kor: "무시하는" },
  { num: 373, unit: 11, eng: "arrogant", kor: "거만한" },
  { num: 374, unit: 11, eng: "limit", kor: "한계; 제한하다" },
  { num: 375, unit: 11, eng: "stable", kor: "안정된" },
  { num: 376, unit: 11, eng: "relationship", kor: "관계" },
  { num: 377, unit: 11, eng: "meaningful", kor: "의미 있는" },
  { num: 378, unit: 11, eng: "public speaking", kor: "대중 연설" },
  { num: 379, unit: 11, eng: "audience", kor: "청중" },
  { num: 380, unit: 11, eng: "monitor", kor: "주시하다" },
  { num: 381, unit: 11, eng: "verbal", kor: "언어적인" },
  { num: 382, unit: 11, eng: "nonverbal", kor: "비언어적인" },
  { num: 383, unit: 11, eng: "assist", kor: "돕다" },
  { num: 384, unit: 11, eng: "memorize", kor: "암기하다, 기억하다" },
  { num: 385, unit: 11, eng: "respectful", kor: "존중하는" },
  { num: 386, unit: 11, eng: "connection", kor: "관계" },
  { num: 387, unit: 11, eng: "grab", kor: "잡다, 움켜쥐다" },
  { num: 388, unit: 11, eng: "drag", kor: "끌고 다니다" },
  { num: 389, unit: 11, eng: "path", kor: "통로, 길" },
  { num: 390, unit: 11, eng: "effect", kor: "효과" },
  { num: 391, unit: 11, eng: "entrance", kor: "입구" },
  { num: 392, unit: 11, eng: "route", kor: "경로, 통로" },
  { num: 393, unit: 11, eng: "checkout", kor: "계산대" },
  { num: 394, unit: 11, eng: "rating", kor: "평점, 등급" },
  { num: 395, unit: 11, eng: "review", kor: "후기, 비평" },
  { num: 396, unit: 11, eng: "purchase", kor: "구매; 구매(구입)하다" },
  { num: 397, unit: 11, eng: "comment", kor: "논평; 의견, 견해" },
  { num: 398, unit: 11, eng: "negative", kor: "부정적인" },
  { num: 399, unit: 11, eng: "interpersonal", kor: "사람과 사람 사이의, 대인간의" },
  { num: 400, unit: 11, eng: "exchange", kor: "의견 교환; 교환" },
  { num: 401, unit: 11, eng: "recommendation", kor: "추천" },
  { num: 402, unit: 11, eng: "potential", kor: "잠재적인, (~이 될) 가능성이 있는" },
  { num: 403, unit: 11, eng: "examine", kor: "검토하다, 조사하다" },
  { num: 404, unit: 11, eng: "habitually", kor: "습관적으로" },
  { num: 405, unit: 11, eng: "press", kor: "강요하다, 압력을 가하다" },
  { num: 406, unit: 11, eng: "diversity", kor: "다양성" },
  { num: 407, unit: 11, eng: "inhabit", kor: "살다" },
  { num: 408, unit: 11, eng: "shape", kor: "형성하다" },
  { num: 409, unit: 11, eng: "in spite of", kor: "~에도 불구하고" },
  { num: 410, unit: 11, eng: "precisely", kor: "바로; 정확히" },
  { num: 411, unit: 12, eng: "appropriate", kor: "적절한, 알맞은" },
  { num: 412, unit: 12, eng: "disclose", kor: "공개하다, 드러내다" },
  { num: 413, unit: 12, eng: "willingness", kor: "기꺼이 하려는 의향(마음)" },
  { num: 414, unit: 12, eng: "harmony", kor: "조화" },
  { num: 415, unit: 12, eng: "improve", kor: "개선하다, 향상시키다" },
  { num: 416, unit: 12, eng: "unfavorable", kor: "불리한" },
  { num: 417, unit: 12, eng: "basic", kor: "기본적인" },
  { num: 418, unit: 12, eng: "normal", kor: "보통의" },
  { num: 419, unit: 12, eng: "adapt to", kor: "~에 적응하다" },
  { num: 420, unit: 12, eng: "environment", kor: "환경" },
  { num: 421, unit: 12, eng: "obstacle", kor: "장애물" },
  { num: 422, unit: 12, eng: "circumstance", kor: "환경" },
  { num: 423, unit: 12, eng: "goal", kor: "목표" },
  { num: 424, unit: 12, eng: "clarify", kor: "분명하게 하다" },
  { num: 425, unit: 12, eng: "analyze", kor: "분석하다" },
  { num: 426, unit: 12, eng: "prove", kor: "증명하다" },
  { num: 427, unit: 12, eng: "develop", kor: "(계획을) 세우다, 수립하다; 발달시키다" },
  { num: 428, unit: 12, eng: "research", kor: "조사하다, 연구하다" },
  { num: 429, unit: 12, eng: "write ~ down", kor: "~을 적다[기록하다]" },
  { num: 430, unit: 12, eng: "vital", kor: "중요한" },
  { num: 431, unit: 12, eng: "unrealistic", kor: "비현실적인" },
  { num: 432, unit: 12, eng: "reward", kor: "보답하다" },
  { num: 433, unit: 12, eng: "realistic", kor: "현실적인" },
  { num: 434, unit: 12, eng: "deal with", kor: "~을 다루다[처리하다]" },
  { num: 435, unit: 12, eng: "preparation", kor: "준비" },
  { num: 436, unit: 12, eng: "confidence", kor: "자신감" },
  { num: 437, unit: 12, eng: "negotiation", kor: "협상" },
  { num: 438, unit: 12, eng: "identify", kor: "알아보다, 확인하다" },
  { num: 439, unit: 12, eng: "value", kor: "소중하게 여기다" },
  { num: 440, unit: 12, eng: "in return", kor: "보답으로" },
  { num: 441, unit: 13, eng: "dramatically", kor: "극적으로" },
  { num: 442, unit: 13, eng: "symbol", kor: "상징" },
  { num: 443, unit: 13, eng: "central", kor: "중심적인, 중심의" },
  { num: 444, unit: 13, eng: "mythology", kor: "신화" },
  { num: 445, unit: 13, eng: "poetry", kor: "시" },
  { num: 446, unit: 13, eng: "ritual", kor: "의식, 의례" },
  { num: 447, unit: 13, eng: "exhibit", kor: "보이다; 전시하다" },
  { num: 448, unit: 13, eng: "opposite", kor: "상반되는; 반대의" },
  { num: 449, unit: 13, eng: "species", kor: "종(생물 분류의 기초 단위)" },
  { num: 450, unit: 13, eng: "honor", kor: "숭배하다" },
  { num: 451, unit: 13, eng: "breed", kor: "기르다" },
  { num: 452, unit: 13, eng: "devotion", kor: "헌신" },
  { num: 453, unit: 13, eng: "association", kor: "협회" },
  { num: 454, unit: 13, eng: "share", kor: "~을 공유하다" },
  { num: 455, unit: 13, eng: "have ~ in common", kor: "~을 공통적으로 지니다" },
  { num: 456, unit: 13, eng: "be into", kor: "~을 좋아하다" },
  { num: 457, unit: 13, eng: "interconnected", kor: "상호 연결된" },
  { num: 458, unit: 13, eng: "hire", kor: "고용하다" },
  { num: 459, unit: 13, eng: "technical", kor: "전문적인; 기술적인" },
  { num: 460, unit: 13, eng: "inspirer", kor: "사기를 불어넣는 사람" },
  { num: 461, unit: 13, eng: "diversify", kor: "다양화하다" },
  { num: 462, unit: 13, eng: "complement", kor: "보완하다" },
  { num: 463, unit: 13, eng: "complex", kor: "복잡한" },
  { num: 464, unit: 13, eng: "equipment", kor: "장비" },
  { num: 465, unit: 13, eng: "instruction", kor: "설명" },
  { num: 466, unit: 13, eng: "surroundings", kor: "환경" },
  { num: 467, unit: 13, eng: "eliminate", kor: "제거하다" },
  { num: 468, unit: 13, eng: "minimum", kor: "최소한도, 최저(치)" },
  { num: 469, unit: 13, eng: "undoubtedly", kor: "의심할 바 없이" },
  { num: 470, unit: 13, eng: "rehearsal", kor: "리허설, (공연) 예행연습" },
  { num: 471, unit: 13, eng: "contribution", kor: "기여" },
  { num: 472, unit: 13, eng: "crew", kor: "단원" },
  { num: 473, unit: 13, eng: "build on", kor: "~을 바탕으로 하다" },
  { num: 474, unit: 13, eng: "accomplishment", kor: "성과, 성취" },
  { num: 475, unit: 13, eng: "nervousness", kor: "긴장감" },
  { num: 476, unit: 13, eng: "overwhelming", kor: "압도적인" },
  { num: 477, unit: 13, eng: "pressure", kor: "압박, 압력" },
  { num: 478, unit: 13, eng: "humor", kor: "기분, 마음" },
  { num: 479, unit: 13, eng: "enthusiasm", kor: "열정" },
  { num: 480, unit: 13, eng: "tackle", kor: "(문제를) 해결하다, 다루다" },
  { num: 481, unit: 14, eng: "evolutionary", kor: "진화적인" },
  { num: 482, unit: 14, eng: "means", kor: "수단" },
  { num: 483, unit: 14, eng: "eye contact", kor: "시선의 마주침" },
  { num: 484, unit: 14, eng: "force", kor: "힘" },
  { num: 485, unit: 14, eng: "arguably", kor: "거의 틀림없이, 주장하건대" },
  { num: 486, unit: 14, eng: "noncooperative", kor: "비협조적인" },
  { num: 487, unit: 14, eng: "cooperative", kor: "협조적인" },
  { num: 488, unit: 14, eng: "rearview mirror", kor: "(자동차의) 백미러" },
  { num: 489, unit: 14, eng: "crow", kor: "까마귀" },
  { num: 490, unit: 14, eng: "remarkably", kor: "놀랄 만큼" },
  { num: 491, unit: 14, eng: "compare", kor: "비교하다" },
  { num: 492, unit: 14, eng: "hatch", kor: "부화하다" },
  { num: 493, unit: 14, eng: "nest", kor: "둥지" },
  { num: 494, unit: 14, eng: "limited", kor: "제한적인" },
  { num: 495, unit: 14, eng: "flexible", kor: "유연한" },
  { num: 496, unit: 14, eng: "extended", kor: "길어진, 연장된" },
  { num: 497, unit: 14, eng: "intelligence", kor: "지능" },
  { num: 498, unit: 14, eng: "initial", kor: "초기의" },
  { num: 499, unit: 14, eng: "rate", kor: "평가하다" },
  { num: 500, unit: 14, eng: "intelligent", kor: "똑똑한" },
  { num: 501, unit: 14, eng: "recall", kor: "기억해내다" },
  { num: 502, unit: 14, eng: "opinion", kor: "의견" },
  { num: 503, unit: 14, eng: "evidence", kor: "증거" },
  { num: 504, unit: 14, eng: "discount", kor: "무시하다, (가치 없는 것으로) 치부하다" },
  { num: 505, unit: 14, eng: "population", kor: "인구, 개체군; 개체 수" },
  { num: 506, unit: 14, eng: "habitat", kor: "서식지" },
  { num: 507, unit: 14, eng: "seek", kor: "찾다, 구하다" },
  { num: 508, unit: 14, eng: "migrate", kor: "이동하다, 이주하다" },
  { num: 509, unit: 14, eng: "continent", kor: "대륙" },
  { num: 510, unit: 14, eng: "wound", kor: "상처" },
  { num: 511, unit: 14, eng: "bullet", kor: "총알" },
  { num: 512, unit: 14, eng: "psychologist", kor: "심리학자" },
  { num: 513, unit: 14, eng: "adolescent", kor: "청소년" },
  { num: 514, unit: 14, eng: "crash", kor: "충돌하다" },
  { num: 515, unit: 14, eng: "randomly", kor: "무작위로" },
  { num: 516, unit: 14, eng: "assign", kor: "(~하도록) 임명하다" },
  { num: 517, unit: 14, eng: "look on", kor: "지켜보다, 구경하다" },
  { num: 518, unit: 14, eng: "peer", kor: "또래" },
  { num: 519, unit: 14, eng: "risky", kor: "위험한; 모험적인" },
  { num: 520, unit: 14, eng: "regardless of", kor: "~에 상관없이" },
  { num: 521, unit: 15, eng: "physical", kor: "신체적인" },
  { num: 522, unit: 15, eng: "processed", kor: "가공된" },
  { num: 523, unit: 15, eng: "chemical", kor: "화학 물질" },
  { num: 524, unit: 15, eng: "artificial", kor: "인공적인" },
  { num: 525, unit: 15, eng: "ingredient", kor: "재료, 성분" },
  { num: 526, unit: 15, eng: "fortunately", kor: "다행히도" },
  { num: 527, unit: 15, eng: "comfort", kor: "편안함" },
  { num: 528, unit: 15, eng: "condition", kor: "조건" },
  { num: 529, unit: 15, eng: "sweat", kor: "땀을 흘리다; 땀" },
  { num: 530, unit: 15, eng: "slide", kor: "빠져 들다; 밀다" },
  { num: 531, unit: 15, eng: "previous", kor: "이전의" },
  { num: 532, unit: 15, eng: "routine", kor: "일상" },
  { num: 533, unit: 15, eng: "pace", kor: "(일의) 속도" },
  { num: 534, unit: 15, eng: "transformation", kor: "변화" },
  { num: 535, unit: 15, eng: "scale", kor: "(지질의) 눈금" },
  { num: 536, unit: 15, eng: "mystery", kor: "신비" },
  { num: 537, unit: 15, eng: "unique", kor: "독특한" },
  { num: 538, unit: 15, eng: "constantly", kor: "끊임없이" },
  { num: 539, unit: 15, eng: "reexamine", kor: "재검토하다" },
  { num: 540, unit: 15, eng: "theory", kor: "이론" },
  { num: 541, unit: 15, eng: "conclusion", kor: "결론" },
  { num: 542, unit: 15, eng: "discovery", kor: "발견" },
  { num: 543, unit: 15, eng: "correct", kor: "바로잡다, 정정하다" },
  { num: 544, unit: 15, eng: "transform", kor: "변화시키다, 바꾸다" },
  { num: 545, unit: 15, eng: "cultural", kor: "문화의" },
  { num: 546, unit: 15, eng: "connectedness", kor: "유대감, 소속감" },
  { num: 547, unit: 15, eng: "isolation", kor: "고립" },
  { num: 548, unit: 15, eng: "forbid", kor: "금지하다" },
  { num: 549, unit: 15, eng: "favor", kor: "선호하다" },
  { num: 550, unit: 15, eng: "attention", kor: "주의(집중)" },
];

const unitTitles = {
  1: "글의 목적 찾기",
  2: "글의 심경·분위기 파악하기",
  3: "도표 정보 파악하기",
  4: "세부 정보 파악하기",
  5: "실용문 정보 파악하기",
  6: "글의 주제·제목 찾기",
  7: "글의 주장·요지 찾기",
  8: "밑줄 친 부분의 의미 파악하기",
  9: "가리키는 대상 찾기",
  10: "빈칸 내용 완성하기",
  11: "무관한 문장 찾기",
  12: "글의 순서 배열하기",
  13: "주어진 문장 위치 파악하기",
  14: "요약문 완성하기",
  15: "알맞은 어법·어휘 찾기",
};